include: package:lints/recommended.yaml

analyzer:
  errors:
    camel_case_extensions: ignore
  exclude: 
    - build/**
  language:
    strict-casts: true

linter:
  rules:
    - prefer_double_quotes
    - cancel_subscriptions
