name: ffi_assist 
description: A helper library for implementations using dart:ffi
version: 0.1.0
repository: https://github.com/scenee/ffi_assist.git

environment:
  sdk: ^3.5.3

dependencies:
  ffi: ^2.1.3

dev_dependencies:
  benchmark_harness: any
  lints: ^4.0.0
  test: ^1.24.0
  yaml: ^3.1.3
